services:

  db:
    image: postgres:16-alpine
    container_name: conthabil_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: conthabil_selenium
    ports:
      - "4444:4444" # Selenium Grid
      - "7900:7900" # noVNC for browser view
    shm_size: 2g

  app:
    build: .
    container_name: conthabil_app
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started


volumes:
  postgres_data:
